-- mem_if_ddr3_emif_0_example_design_example_sim_e0_if0_mm_interconnect_0.vhd

-- This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 14.0 200 at 2016.05.21.21:53:44

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mem_if_ddr3_emif_0_example_design_example_sim_e0_if0_mm_interconnect_0 is
	port (
		p0_avl_clk_clk                                              : in  std_logic                     := '0';             --                                            p0_avl_clk.clk
		dmaster_clk_reset_reset_bridge_in_reset_reset               : in  std_logic                     := '0';             --               dmaster_clk_reset_reset_bridge_in_reset.reset
		dmaster_master_translator_reset_reset_bridge_in_reset_reset : in  std_logic                     := '0';             -- dmaster_master_translator_reset_reset_bridge_in_reset.reset
		dmaster_master_address                                      : in  std_logic_vector(31 downto 0) := (others => '0'); --                                        dmaster_master.address
		dmaster_master_waitrequest                                  : out std_logic;                                        --                                                      .waitrequest
		dmaster_master_byteenable                                   : in  std_logic_vector(3 downto 0)  := (others => '0'); --                                                      .byteenable
		dmaster_master_read                                         : in  std_logic                     := '0';             --                                                      .read
		dmaster_master_readdata                                     : out std_logic_vector(31 downto 0);                    --                                                      .readdata
		dmaster_master_readdatavalid                                : out std_logic;                                        --                                                      .readdatavalid
		dmaster_master_write                                        : in  std_logic                     := '0';             --                                                      .write
		dmaster_master_writedata                                    : in  std_logic_vector(31 downto 0) := (others => '0'); --                                                      .writedata
		s0_seq_debug_address                                        : out std_logic_vector(31 downto 0);                    --                                          s0_seq_debug.address
		s0_seq_debug_write                                          : out std_logic;                                        --                                                      .write
		s0_seq_debug_read                                           : out std_logic;                                        --                                                      .read
		s0_seq_debug_readdata                                       : in  std_logic_vector(31 downto 0) := (others => '0'); --                                                      .readdata
		s0_seq_debug_writedata                                      : out std_logic_vector(31 downto 0);                    --                                                      .writedata
		s0_seq_debug_burstcount                                     : out std_logic_vector(0 downto 0);                     --                                                      .burstcount
		s0_seq_debug_byteenable                                     : out std_logic_vector(3 downto 0);                     --                                                      .byteenable
		s0_seq_debug_readdatavalid                                  : in  std_logic                     := '0';             --                                                      .readdatavalid
		s0_seq_debug_waitrequest                                    : in  std_logic                     := '0'              --                                                      .waitrequest
	);
end entity mem_if_ddr3_emif_0_example_design_example_sim_e0_if0_mm_interconnect_0;

architecture rtl of mem_if_ddr3_emif_0_example_design_example_sim_e0_if0_mm_interconnect_0 is
	component altera_merlin_master_translator is
		generic (
			AV_ADDRESS_W                : integer := 32;
			AV_DATA_W                   : integer := 32;
			AV_BURSTCOUNT_W             : integer := 4;
			AV_BYTEENABLE_W             : integer := 4;
			UAV_ADDRESS_W               : integer := 38;
			UAV_BURSTCOUNT_W            : integer := 10;
			USE_READ                    : integer := 1;
			USE_WRITE                   : integer := 1;
			USE_BEGINBURSTTRANSFER      : integer := 0;
			USE_BEGINTRANSFER           : integer := 0;
			USE_CHIPSELECT              : integer := 0;
			USE_BURSTCOUNT              : integer := 1;
			USE_READDATAVALID           : integer := 1;
			USE_WAITREQUEST             : integer := 1;
			USE_READRESPONSE            : integer := 0;
			USE_WRITERESPONSE           : integer := 0;
			AV_SYMBOLS_PER_WORD         : integer := 4;
			AV_ADDRESS_SYMBOLS          : integer := 0;
			AV_BURSTCOUNT_SYMBOLS       : integer := 0;
			AV_CONSTANT_BURST_BEHAVIOR  : integer := 0;
			UAV_CONSTANT_BURST_BEHAVIOR : integer := 0;
			AV_LINEWRAPBURSTS           : integer := 0;
			AV_REGISTERINCOMINGSIGNALS  : integer := 0
		);
		port (
			clk                      : in  std_logic                     := 'X';             -- clk
			reset                    : in  std_logic                     := 'X';             -- reset
			uav_address              : out std_logic_vector(31 downto 0);                    -- address
			uav_burstcount           : out std_logic_vector(2 downto 0);                     -- burstcount
			uav_read                 : out std_logic;                                        -- read
			uav_write                : out std_logic;                                        -- write
			uav_waitrequest          : in  std_logic                     := 'X';             -- waitrequest
			uav_readdatavalid        : in  std_logic                     := 'X';             -- readdatavalid
			uav_byteenable           : out std_logic_vector(3 downto 0);                     -- byteenable
			uav_readdata             : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			uav_writedata            : out std_logic_vector(31 downto 0);                    -- writedata
			uav_lock                 : out std_logic;                                        -- lock
			uav_debugaccess          : out std_logic;                                        -- debugaccess
			av_address               : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			av_waitrequest           : out std_logic;                                        -- waitrequest
			av_byteenable            : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			av_read                  : in  std_logic                     := 'X';             -- read
			av_readdata              : out std_logic_vector(31 downto 0);                    -- readdata
			av_readdatavalid         : out std_logic;                                        -- readdatavalid
			av_write                 : in  std_logic                     := 'X';             -- write
			av_writedata             : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			av_burstcount            : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- burstcount
			av_beginbursttransfer    : in  std_logic                     := 'X';             -- beginbursttransfer
			av_begintransfer         : in  std_logic                     := 'X';             -- begintransfer
			av_chipselect            : in  std_logic                     := 'X';             -- chipselect
			av_lock                  : in  std_logic                     := 'X';             -- lock
			av_debugaccess           : in  std_logic                     := 'X';             -- debugaccess
			uav_clken                : out std_logic;                                        -- clken
			av_clken                 : in  std_logic                     := 'X';             -- clken
			uav_response             : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			av_response              : out std_logic_vector(1 downto 0);                     -- response
			uav_writeresponserequest : out std_logic;                                        -- writeresponserequest
			uav_writeresponsevalid   : in  std_logic                     := 'X';             -- writeresponsevalid
			av_writeresponserequest  : in  std_logic                     := 'X';             -- writeresponserequest
			av_writeresponsevalid    : out std_logic                                         -- writeresponsevalid
		);
	end component altera_merlin_master_translator;

	component altera_merlin_slave_translator is
		generic (
			AV_ADDRESS_W                   : integer := 30;
			AV_DATA_W                      : integer := 32;
			UAV_DATA_W                     : integer := 32;
			AV_BURSTCOUNT_W                : integer := 4;
			AV_BYTEENABLE_W                : integer := 4;
			UAV_BYTEENABLE_W               : integer := 4;
			UAV_ADDRESS_W                  : integer := 32;
			UAV_BURSTCOUNT_W               : integer := 4;
			AV_READLATENCY                 : integer := 0;
			USE_READDATAVALID              : integer := 1;
			USE_WAITREQUEST                : integer := 1;
			USE_UAV_CLKEN                  : integer := 0;
			USE_READRESPONSE               : integer := 0;
			USE_WRITERESPONSE              : integer := 0;
			AV_SYMBOLS_PER_WORD            : integer := 4;
			AV_ADDRESS_SYMBOLS             : integer := 0;
			AV_BURSTCOUNT_SYMBOLS          : integer := 0;
			AV_CONSTANT_BURST_BEHAVIOR     : integer := 0;
			UAV_CONSTANT_BURST_BEHAVIOR    : integer := 0;
			AV_REQUIRE_UNALIGNED_ADDRESSES : integer := 0;
			CHIPSELECT_THROUGH_READLATENCY : integer := 0;
			AV_READ_WAIT_CYCLES            : integer := 0;
			AV_WRITE_WAIT_CYCLES           : integer := 0;
			AV_SETUP_WAIT_CYCLES           : integer := 0;
			AV_DATA_HOLD_CYCLES            : integer := 0
		);
		port (
			clk                      : in  std_logic                     := 'X';             -- clk
			reset                    : in  std_logic                     := 'X';             -- reset
			uav_address              : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			uav_burstcount           : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- burstcount
			uav_read                 : in  std_logic                     := 'X';             -- read
			uav_write                : in  std_logic                     := 'X';             -- write
			uav_waitrequest          : out std_logic;                                        -- waitrequest
			uav_readdatavalid        : out std_logic;                                        -- readdatavalid
			uav_byteenable           : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			uav_readdata             : out std_logic_vector(31 downto 0);                    -- readdata
			uav_writedata            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			uav_lock                 : in  std_logic                     := 'X';             -- lock
			uav_debugaccess          : in  std_logic                     := 'X';             -- debugaccess
			av_address               : out std_logic_vector(31 downto 0);                    -- address
			av_write                 : out std_logic;                                        -- write
			av_read                  : out std_logic;                                        -- read
			av_readdata              : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			av_writedata             : out std_logic_vector(31 downto 0);                    -- writedata
			av_burstcount            : out std_logic_vector(0 downto 0);                     -- burstcount
			av_byteenable            : out std_logic_vector(3 downto 0);                     -- byteenable
			av_readdatavalid         : in  std_logic                     := 'X';             -- readdatavalid
			av_waitrequest           : in  std_logic                     := 'X';             -- waitrequest
			av_begintransfer         : out std_logic;                                        -- begintransfer
			av_beginbursttransfer    : out std_logic;                                        -- beginbursttransfer
			av_writebyteenable       : out std_logic_vector(3 downto 0);                     -- writebyteenable
			av_lock                  : out std_logic;                                        -- lock
			av_chipselect            : out std_logic;                                        -- chipselect
			av_clken                 : out std_logic;                                        -- clken
			uav_clken                : in  std_logic                     := 'X';             -- clken
			av_debugaccess           : out std_logic;                                        -- debugaccess
			av_outputenable          : out std_logic;                                        -- outputenable
			uav_response             : out std_logic_vector(1 downto 0);                     -- response
			av_response              : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			uav_writeresponserequest : in  std_logic                     := 'X';             -- writeresponserequest
			uav_writeresponsevalid   : out std_logic;                                        -- writeresponsevalid
			av_writeresponserequest  : out std_logic;                                        -- writeresponserequest
			av_writeresponsevalid    : in  std_logic                     := 'X'              -- writeresponsevalid
		);
	end component altera_merlin_slave_translator;

	signal dmaster_master_translator_avalon_universal_master_0_waitrequest   : std_logic;                     -- s0_seq_debug_translator:uav_waitrequest -> dmaster_master_translator:uav_waitrequest
	signal dmaster_master_translator_avalon_universal_master_0_burstcount    : std_logic_vector(2 downto 0);  -- dmaster_master_translator:uav_burstcount -> s0_seq_debug_translator:uav_burstcount
	signal dmaster_master_translator_avalon_universal_master_0_writedata     : std_logic_vector(31 downto 0); -- dmaster_master_translator:uav_writedata -> s0_seq_debug_translator:uav_writedata
	signal dmaster_master_translator_avalon_universal_master_0_address       : std_logic_vector(31 downto 0); -- dmaster_master_translator:uav_address -> s0_seq_debug_translator:uav_address
	signal dmaster_master_translator_avalon_universal_master_0_lock          : std_logic;                     -- dmaster_master_translator:uav_lock -> s0_seq_debug_translator:uav_lock
	signal dmaster_master_translator_avalon_universal_master_0_write         : std_logic;                     -- dmaster_master_translator:uav_write -> s0_seq_debug_translator:uav_write
	signal dmaster_master_translator_avalon_universal_master_0_read          : std_logic;                     -- dmaster_master_translator:uav_read -> s0_seq_debug_translator:uav_read
	signal dmaster_master_translator_avalon_universal_master_0_readdata      : std_logic_vector(31 downto 0); -- s0_seq_debug_translator:uav_readdata -> dmaster_master_translator:uav_readdata
	signal dmaster_master_translator_avalon_universal_master_0_debugaccess   : std_logic;                     -- dmaster_master_translator:uav_debugaccess -> s0_seq_debug_translator:uav_debugaccess
	signal dmaster_master_translator_avalon_universal_master_0_byteenable    : std_logic_vector(3 downto 0);  -- dmaster_master_translator:uav_byteenable -> s0_seq_debug_translator:uav_byteenable
	signal dmaster_master_translator_avalon_universal_master_0_readdatavalid : std_logic;                     -- s0_seq_debug_translator:uav_readdatavalid -> dmaster_master_translator:uav_readdatavalid

begin

	dmaster_master_translator : component altera_merlin_master_translator
		generic map (
			AV_ADDRESS_W                => 32,
			AV_DATA_W                   => 32,
			AV_BURSTCOUNT_W             => 1,
			AV_BYTEENABLE_W             => 4,
			UAV_ADDRESS_W               => 32,
			UAV_BURSTCOUNT_W            => 3,
			USE_READ                    => 1,
			USE_WRITE                   => 1,
			USE_BEGINBURSTTRANSFER      => 0,
			USE_BEGINTRANSFER           => 0,
			USE_CHIPSELECT              => 0,
			USE_BURSTCOUNT              => 0,
			USE_READDATAVALID           => 1,
			USE_WAITREQUEST             => 1,
			USE_READRESPONSE            => 0,
			USE_WRITERESPONSE           => 0,
			AV_SYMBOLS_PER_WORD         => 4,
			AV_ADDRESS_SYMBOLS          => 1,
			AV_BURSTCOUNT_SYMBOLS       => 0,
			AV_CONSTANT_BURST_BEHAVIOR  => 0,
			UAV_CONSTANT_BURST_BEHAVIOR => 0,
			AV_LINEWRAPBURSTS           => 0,
			AV_REGISTERINCOMINGSIGNALS  => 0
		)
		port map (
			clk                      => p0_avl_clk_clk,                                                    --                       clk.clk
			reset                    => dmaster_master_translator_reset_reset_bridge_in_reset_reset,       --                     reset.reset
			uav_address              => dmaster_master_translator_avalon_universal_master_0_address,       -- avalon_universal_master_0.address
			uav_burstcount           => dmaster_master_translator_avalon_universal_master_0_burstcount,    --                          .burstcount
			uav_read                 => dmaster_master_translator_avalon_universal_master_0_read,          --                          .read
			uav_write                => dmaster_master_translator_avalon_universal_master_0_write,         --                          .write
			uav_waitrequest          => dmaster_master_translator_avalon_universal_master_0_waitrequest,   --                          .waitrequest
			uav_readdatavalid        => dmaster_master_translator_avalon_universal_master_0_readdatavalid, --                          .readdatavalid
			uav_byteenable           => dmaster_master_translator_avalon_universal_master_0_byteenable,    --                          .byteenable
			uav_readdata             => dmaster_master_translator_avalon_universal_master_0_readdata,      --                          .readdata
			uav_writedata            => dmaster_master_translator_avalon_universal_master_0_writedata,     --                          .writedata
			uav_lock                 => dmaster_master_translator_avalon_universal_master_0_lock,          --                          .lock
			uav_debugaccess          => dmaster_master_translator_avalon_universal_master_0_debugaccess,   --                          .debugaccess
			av_address               => dmaster_master_address,                                            --      avalon_anti_master_0.address
			av_waitrequest           => dmaster_master_waitrequest,                                        --                          .waitrequest
			av_byteenable            => dmaster_master_byteenable,                                         --                          .byteenable
			av_read                  => dmaster_master_read,                                               --                          .read
			av_readdata              => dmaster_master_readdata,                                           --                          .readdata
			av_readdatavalid         => dmaster_master_readdatavalid,                                      --                          .readdatavalid
			av_write                 => dmaster_master_write,                                              --                          .write
			av_writedata             => dmaster_master_writedata,                                          --                          .writedata
			av_burstcount            => "1",                                                               --               (terminated)
			av_beginbursttransfer    => '0',                                                               --               (terminated)
			av_begintransfer         => '0',                                                               --               (terminated)
			av_chipselect            => '0',                                                               --               (terminated)
			av_lock                  => '0',                                                               --               (terminated)
			av_debugaccess           => '0',                                                               --               (terminated)
			uav_clken                => open,                                                              --               (terminated)
			av_clken                 => '1',                                                               --               (terminated)
			uav_response             => "00",                                                              --               (terminated)
			av_response              => open,                                                              --               (terminated)
			uav_writeresponserequest => open,                                                              --               (terminated)
			uav_writeresponsevalid   => '0',                                                               --               (terminated)
			av_writeresponserequest  => '0',                                                               --               (terminated)
			av_writeresponsevalid    => open                                                               --               (terminated)
		);

	s0_seq_debug_translator : component altera_merlin_slave_translator
		generic map (
			AV_ADDRESS_W                   => 32,
			AV_DATA_W                      => 32,
			UAV_DATA_W                     => 32,
			AV_BURSTCOUNT_W                => 1,
			AV_BYTEENABLE_W                => 4,
			UAV_BYTEENABLE_W               => 4,
			UAV_ADDRESS_W                  => 32,
			UAV_BURSTCOUNT_W               => 3,
			AV_READLATENCY                 => 0,
			USE_READDATAVALID              => 1,
			USE_WAITREQUEST                => 1,
			USE_UAV_CLKEN                  => 0,
			USE_READRESPONSE               => 0,
			USE_WRITERESPONSE              => 0,
			AV_SYMBOLS_PER_WORD            => 4,
			AV_ADDRESS_SYMBOLS             => 1,
			AV_BURSTCOUNT_SYMBOLS          => 0,
			AV_CONSTANT_BURST_BEHAVIOR     => 0,
			UAV_CONSTANT_BURST_BEHAVIOR    => 0,
			AV_REQUIRE_UNALIGNED_ADDRESSES => 0,
			CHIPSELECT_THROUGH_READLATENCY => 0,
			AV_READ_WAIT_CYCLES            => 1,
			AV_WRITE_WAIT_CYCLES           => 0,
			AV_SETUP_WAIT_CYCLES           => 0,
			AV_DATA_HOLD_CYCLES            => 0
		)
		port map (
			clk                      => p0_avl_clk_clk,                                                    --                      clk.clk
			reset                    => dmaster_master_translator_reset_reset_bridge_in_reset_reset,       --                    reset.reset
			uav_address              => dmaster_master_translator_avalon_universal_master_0_address,       -- avalon_universal_slave_0.address
			uav_burstcount           => dmaster_master_translator_avalon_universal_master_0_burstcount,    --                         .burstcount
			uav_read                 => dmaster_master_translator_avalon_universal_master_0_read,          --                         .read
			uav_write                => dmaster_master_translator_avalon_universal_master_0_write,         --                         .write
			uav_waitrequest          => dmaster_master_translator_avalon_universal_master_0_waitrequest,   --                         .waitrequest
			uav_readdatavalid        => dmaster_master_translator_avalon_universal_master_0_readdatavalid, --                         .readdatavalid
			uav_byteenable           => dmaster_master_translator_avalon_universal_master_0_byteenable,    --                         .byteenable
			uav_readdata             => dmaster_master_translator_avalon_universal_master_0_readdata,      --                         .readdata
			uav_writedata            => dmaster_master_translator_avalon_universal_master_0_writedata,     --                         .writedata
			uav_lock                 => dmaster_master_translator_avalon_universal_master_0_lock,          --                         .lock
			uav_debugaccess          => dmaster_master_translator_avalon_universal_master_0_debugaccess,   --                         .debugaccess
			av_address               => s0_seq_debug_address,                                              --      avalon_anti_slave_0.address
			av_write                 => s0_seq_debug_write,                                                --                         .write
			av_read                  => s0_seq_debug_read,                                                 --                         .read
			av_readdata              => s0_seq_debug_readdata,                                             --                         .readdata
			av_writedata             => s0_seq_debug_writedata,                                            --                         .writedata
			av_burstcount            => s0_seq_debug_burstcount,                                           --                         .burstcount
			av_byteenable            => s0_seq_debug_byteenable,                                           --                         .byteenable
			av_readdatavalid         => s0_seq_debug_readdatavalid,                                        --                         .readdatavalid
			av_waitrequest           => s0_seq_debug_waitrequest,                                          --                         .waitrequest
			av_begintransfer         => open,                                                              --              (terminated)
			av_beginbursttransfer    => open,                                                              --              (terminated)
			av_writebyteenable       => open,                                                              --              (terminated)
			av_lock                  => open,                                                              --              (terminated)
			av_chipselect            => open,                                                              --              (terminated)
			av_clken                 => open,                                                              --              (terminated)
			uav_clken                => '0',                                                               --              (terminated)
			av_debugaccess           => open,                                                              --              (terminated)
			av_outputenable          => open,                                                              --              (terminated)
			uav_response             => open,                                                              --              (terminated)
			av_response              => "00",                                                              --              (terminated)
			uav_writeresponserequest => '0',                                                               --              (terminated)
			uav_writeresponsevalid   => open,                                                              --              (terminated)
			av_writeresponserequest  => open,                                                              --              (terminated)
			av_writeresponsevalid    => '0'                                                                --              (terminated)
		);

end architecture rtl; -- of mem_if_ddr3_emif_0_example_design_example_sim_e0_if0_mm_interconnect_0
